spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgresdb
    password: abcd1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: 'true'
        format_sql: 'true'
        use_sql_comments: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: update
server:
  port: '8081'
